# -*- coding: utf-8 -*-
"""python 1 day .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c7YtRov31XDTQXVE-2aDVPdcTMWJub3j

hi i am writing python code

SHIFT + enter -- next line

ctrl + enter same line

program

type of DATA

1. INT

WHOLE number (+ve) - does not have decimal
"""

population = 314313131313
print(population)

## variable

unemployment_ratessssssss = 3654384646

print(unemployment_ratessssssss)

years_until_2030 = 2030 - 2025

print(years_until_2030)

type(years_until_2030)

"""2. FLOAT

DECIMAL points
"""

inflation_rate = 5.42
gdp_growth = 6.3

print("THe inflation rate today is = " , inflation_rate   )

"""3. STRING

text
"""

name = "Divesh"

print(name)
print("His name issssss" , name )

type(name)

"""LIST

List of values , sperated with a comma


mutable
"""

foods = ["pizza" , 15 , 6.3 ]

print(foods)

type(foods)

"""how list solves my problme"""

numbers = [ 346 , 420 , 123 , 25 , 503 , 96 ]
print(numbers)
numbers.append(69)
print(numbers)
numbers.pop()
print(numbers)
numbers.pop(2)
print(numbers)

print(sorted(numbers))

"""TUPLE

immutable
"""

number = ( 1 , 6 , "hi" , 3.7 )
print(number)

type(number)

